# Generated by Django 3.2.8 on 2021-10-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaldashboard', '0005_auto_20211030_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
