# Generated by Django 3.2.8 on 2021-11-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaldashboard', '0008_question_answer_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_desc',
            new_name='desc',
        ),
    ]
