# Generated by Django 3.2.8 on 2021-11-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaldashboard', '0009_rename_answer_desc_question_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
