# Generated by Django 3.2.8 on 2021-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaldashboard', '0010_auto_20211114_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
